#!/bin/bash

if [[ $# -lt 2 ]]; then
  echo Usage: "$0" [url] [cookie]
  exit 1
fi

url=$1
cookie=$2

docker run --rm -i -p 1080:1080 --name openconnect --cap-add=NET_ADMIN $(docker build -q .) -C "webvpn=$2" "$1"

