#!/bin/bash

if [[ $# -lt 4 ]]; then
  echo Usage: "$0" [url] [authgroup] [username] [password]
  exit 1
fi

url=$1
authgroup=$2
username=$3
password=$4

echo "$4" | docker run --rm -i -p 1080:1080 --name openconnect --cap-add=NET_ADMIN $(docker build -q .) --user "$3" -passwd-on-stdin --authgroup "$2" "$1"

